#finally block

#finally block always work

#with or without exception

#try block and finally bolck always works

#except block work only when an exception occured

#order

#try:
#exception:
#finally:

a=[1,2,3]
i=int(input("Enter an index value"))

try:
       print(a[i])
except:
    print("out of range")
finally:
    print("inside finally")